DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;

-- 글번호 그룹번호 그룹순서 제목공백 제목 내용 작성자 작성일
CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER NOT NULL,
	GROUPNO NUMBER NOT NULL,
	GROUPSEQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	DELFLAG VARCHAR(2) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(100) NOT NULL,
	REGDATE DATE NOT NULL,
	--제약조건 1 : BOARDNO에 ANSWER_BOARDNO_PK 라는 이름으로 PK 걸자
	CONSTRAINT ANSWER_BOARDNO_PK PRIMARY KEY (BOARDNO),
	-- 제약조건 2 : DELFLAG에 ANSWER_DELFLAG_CK 라는 이름으로 CHECK 걸자('Y', 'N')
	CONSTRAINT ANSWER_DELFLAG_CK CHECK(DELFLAG IN ('Y', 'N'))
);

-- 출력
SELECT BOARDNO, GROUPNO, GROUPSEQ, TITLETAB, DELFLAG, TITLE, CONTENT, WRITER, REGDATE
FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSEQ;


-- 1번글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, 'N',
	'답변형 재밌다', '정말재밌다.', '반장', SYSDATE);

-- 1번글에 답글
-- UPDATE
UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ + 1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = ?)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = ?);
	
-- INSERT

INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1) + 1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO = 1) + 1,
	'N',
	'RE:답변형 재밌다.',
	'진짜 재밌는거 맞아?',
	'강사',
	SYSDATE
	);
	
-- 1번 글 삭제
UPDATE ANSWERBOARD
SET DELFLAG = 'Y'
WHERE BOARDNO = 1;
	